import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';import {scryptSync} from 'node:crypto';import sharp from 'sharp';
const directory=fs.mkdtempSync(path.join(os.tmpdir(),'ly-product-test-'));Object.assign(process.env,{DATA_DIR:directory,NODE_ENV:'test',ADMIN_USERNAME:'ly',ADMIN_PASSWORD_HASH:'scrypt:fixture:'+scryptSync('fixture-password','fixture',64).toString('hex')});const {handler,initializeData}=await import('../server.mjs');initializeData();const server=http.createServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;let groups=0;const headers={'Content-Type':'application/json',Origin:base,'X-Requested-With':'rqly-editor'};const login=await fetch(base+'/api/auth/login',{method:'POST',headers,body:JSON.stringify({username:'ly',password:'fixture-password'})});headers.Cookie=login.headers.get('set-cookie').split(';')[0];headers['X-CSRF-Token']=(await login.json()).csrfToken;const req=(route,method='GET',data,extra={})=>fetch(base+route,{method,headers:{...headers,...extra},...(data?{body:JSON.stringify(data)}:{})});const png=await sharp({create:{width:120,height:80,channels:3,background:'#829971'}}).png().toBuffer();const upload=async()=>{const r=await fetch(base+'/api/admin/media',{method:'POST',headers:{...headers,'Content-Type':'image/png'},body:png});assert.equal(r.status,201);return(await r.json()).image;};
try{
 assert.equal((await fetch(base+'/api/admin/export')).status,401);assert.equal((await fetch(base+'/api/admin/media/00000000000000000000000000000000.webp',{method:'DELETE'})).status,401);groups++;
 const image=await upload();const content={title:'独立封面',body:'## 正文\n这篇文章仅使用封面。',cover:image.url,kind:'blog',published:false};let r=await req('/api/admin/posts','POST',content);assert.equal(r.status,200);let post=(await r.json()).post;assert.equal((await fetch(base+image.url)).status,404);groups++;
 r=await req('/api/admin/posts','PUT',{...post,published:true},{'If-Match':post.revision});post=(await r.json()).post;assert.equal((await fetch(base+image.url)).status,200);const pub=(await(await fetch(base+'/api/posts/'+post.slug)).json()).post;assert.equal(pub.cover,image.url);assert(!pub.revision);assert((await(await fetch(base+'/notes/'+post.slug)).text()).includes('article-cover'));groups++;
 let library=(await(await req('/api/admin/media')).json());assert.equal(library.storage.count,1);assert.equal(library.images[0].references[0].status,'published');assert.equal((await req('/api/admin/media/'+image.filename,'DELETE')).status,409);groups++;
 r=await req('/api/admin/posts','PUT',{...post,published:false},{'If-Match':post.revision});post=(await r.json()).post;assert.equal((await fetch(base+image.url)).status,404);assert.equal((await req('/api/admin/media/'+image.filename,'DELETE')).status,409);r=await req('/api/admin/posts/'+post.slug,'DELETE',null,{'If-Match':post.revision});assert.equal(r.status,200);assert.equal((await req('/api/admin/media/'+image.filename,'DELETE')).status,409);groups++;
 const unused=await upload();assert.equal((await req('/api/admin/media?unused=1')).status,200);library=await(await req('/api/admin/media?unused=1')).json();assert.equal(library.images.length,1);assert.equal(library.images[0].filename,unused.filename);assert.equal((await req('/api/admin/media/'+unused.filename,'DELETE',null,{'X-CSRF-Token':''})).status,403);assert.equal((await req('/api/admin/media/'+unused.filename,'DELETE')).status,200);assert.equal((await req(unused.url)).status,404);groups++;
 const draftImage=await upload();const raw={title:'',body:'',summary:'',slug:'',date:'',kind:'note',topic:'记录',cover:draftImage.url,project:{status:'active',role:'',period:''}};r=await req('/api/admin/editor-drafts/new-cover-test','PUT',{baseRevision:null,sourceSlug:null,sourceRevision:null,content:raw});assert.equal(r.status,200);assert.equal((await req('/api/admin/media/'+draftImage.filename,'DELETE')).status,409);assert((await(await req('/api/admin/media')).json()).images.some(i=>i.references.some(ref=>ref.type==='editorDraft')));groups++;
 const islandBefore=fs.readFileSync(path.join(directory,'island.json'));initializeData();assert(fs.readFileSync(path.join(directory,'island.json')).equals(islandBefore));let state=(await(await req('/api/admin/island')).json()).island;let bad={...state,phase:'grown',growth:{threshold:30,unlocked:true}};assert.equal((await req('/api/admin/island','PUT',{baseRevision:state.revision,island:bad})).status,409);groups++;
 const data={title:'完工项目',body:'成果记录',kind:'project',published:true,project:{status:'done'}};r=await req('/api/admin/posts','POST',data);let project=(await r.json()).post;let stats=(await(await req('/api/island')).json()).stats;assert.equal(stats.completed,1);assert.equal(stats.score,24);r=await req('/api/admin/posts','PUT',project,{'If-Match':project.revision});project=(await r.json()).post;assert.equal((await(await req('/api/island')).json()).stats.score,24);groups++;
 state.growth.threshold=20;state.phase='grown';state.decorations=[{slot:'west',type:'bench'},{slot:'east',type:'lamp'}];r=await req('/api/admin/island','PUT',{baseRevision:state.revision,island:state});assert.equal(r.status,200);state=(await r.json()).island;assert.equal(state.growth.unlocked,true);assert.equal(state.decorations.length,2);assert.equal((await req('/api/admin/island','PUT',{baseRevision:0,island:state})).status,409);groups++;
 r=await req('/api/admin/posts','PUT',{...project,published:false},{'If-Match':project.revision});assert.equal(r.status,200);stats=(await(await req('/api/island')).json()).stats;assert.equal(stats.score,9);assert.equal(stats.stage,2);assert.equal(stats.unlocked,true);state.phase='initial';r=await req('/api/admin/island','PUT',{baseRevision:state.revision,island:state});state=(await r.json()).island;state.phase='grown';assert.equal((await req('/api/admin/island','PUT',{baseRevision:state.revision,island:state})).status,200);groups++;
 state=(await(await req('/api/admin/island')).json()).island;for(const decorations of [[{slot:'bad',type:'tree'}],[{slot:'west',type:'tree'},{slot:'west',type:'lamp'}],[{slot:'west',type:'script'}]])assert.equal((await req('/api/admin/island','PUT',{baseRevision:state.revision,island:{...state,decorations}})).status,400);assert.equal((await req('/api/admin/posts','POST',{...content,cover:'https://external.example/a.png'})).status,400);assert.equal((await req('/api/admin/posts','POST',{...content,cover:unused.url})).status,409);groups++;
 const exported=await(await req('/api/admin/export')).json();assert.equal(exported.schemaVersion,1);assert(exported.posts.some(p=>p.cover===image.url));assert.equal(exported.editorDrafts[0].content.cover,draftImage.url);assert.equal(exported.island.decorations.length,2);assert(!JSON.stringify(exported).includes('passwordHash'));assert.equal((await req('/qizui/api/admin/export')).status,404);groups++;
 const metadata=JSON.parse(fs.readFileSync(path.join(directory,'media',draftImage.filename+'.json')));for(let i=1;i<=61;i++){const filename=i.toString(16).padStart(32,'0')+'.webp';fs.copyFileSync(path.join(directory,'media',draftImage.filename),path.join(directory,'media',filename));fs.writeFileSync(path.join(directory,'media',filename+'.json'),JSON.stringify({...metadata,filename,url:'/media/'+filename}),{mode:0o600});}const first=await(await req('/api/admin/media')).json();assert.equal(first.images.length,60);assert.equal(first.nextOffset,60);const second=await(await req('/api/admin/media?offset=60')).json();assert.equal(second.images.length,3);assert.equal(second.nextOffset,null);assert.equal(new Set([...first.images,...second.images].map(i=>i.filename)).size,63);groups++;
 console.log(groups+' product groups passed: covers/privacy/references, safe deletion/CSRF, draft references, real growth/confirmation/no duplicate credit/unlock persistence, decorations and private export.');
}finally{await new Promise(r=>server.close(r));fs.rmSync(directory,{recursive:true,force:true});}
