import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
class Element{constructor(){this.listeners={};this.hidden=false;this.value='';this.type='password';this.textContent='';this.classList={add(){},remove(){},toggle(){}};}addEventListener(name,handler){this.listeners[name]=handler;}setAttribute(){}removeAttribute(name){delete this[name];}focus(){this.focused=true;}}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
// Execute the real login code: a valid password alone must never redirect in the MFA step.
let nodes=new Map();const get=id=>{if(!nodes.has(id))nodes.set(id,new Element());return nodes.get(id);};let step=0,redirect=null;const events={};get('login-mfa-label').hidden=true;get('login-username').value='ly';get('login-password').value='isolated-password';
vm.runInNewContext(fs.readFileSync(new URL('../public/rqly/login.js',import.meta.url),'utf8'),{document:{getElementById:get},URLSearchParams,window:{addEventListener:(name,fn)=>events[name]=fn},location:{search:'',hostname:'rqly.com',replace:dest=>redirect=dest},fetch:async(route,options)=>{if(route==='/api/auth/session')return {json:async()=>({authenticated:false})};const body=JSON.parse(options.body);if(step++===0){assert.equal(body.code,'');return {ok:false,json:async()=>({code:'MFA_REQUIRED',error:'请输入验证码'})};}assert.equal(body.code,'123456');return {ok:true,json:async()=>({authenticated:true})};}});
await get('login-form').listeners.submit({preventDefault(){}});assert.equal(redirect,null);assert.equal(get('login-mfa-label').hidden,false);assert(get('login-mfa-code').focused);get('login-mfa-code').value='123456';await get('login-form').listeners.submit({preventDefault(){}});assert.equal(redirect,'/admin');assert.equal(get('login-password').value,'');assert.equal(get('login-mfa-code').value,'');
// Execute the actual account panel and ensure secrets disappear when leaving account settings.
nodes=new Map();let observe,confirmed=false,disabled=false;const dispatched=[];const fake={pendingId:'fixture',secret:'ONLY-IN-BINDING',qrCode:'data:image/png;base64,fixture',recoveryCodes:['ONE-TIME-RECOVERY']};
const context={document:{getElementById:get,querySelectorAll:()=>[],createElement:()=>new Element()},MutationObserver:class{constructor(callback){observe=callback;}observe(){}},Event:class{constructor(type){this.type=type;}},window:{confirm:()=>confirmed,addEventListener(){},dispatchEvent:event=>dispatched.push(event.type)},fetch:async(route,options={})=>{if(route==='/api/auth/session')return {json:async()=>({authenticated:true,csrfToken:'fixture'})};assert.equal(options.headers['X-CSRF-Token'],'fixture');if(route.endsWith('/setup'))return {ok:true,json:async()=>fake};if(route.endsWith('/confirm')){assert.equal(JSON.parse(options.body).recoverySaved,true);return {ok:true,json:async()=>({enabled:true,recoveryCodesRemaining:10,csrfToken:'new-fixture'})};}if(route.endsWith('/disable'))disabled=true;return {ok:true,json:async()=>({enabled:false,recoveryCodesRemaining:0})};}};
vm.runInNewContext(fs.readFileSync(new URL('../public/rqly/admin-mfa.js',import.meta.url),'utf8'),context);await tick();get('mfa-password').value='password';get('mfa-start').listeners.click();await tick();await tick();assert.equal(get('mfa-secret').textContent,fake.secret);assert.equal(get('mfa-recovery-codes').textContent,'ONE-TIME-RECOVERY');assert.equal(get('mfa-password').value,'');get('mfa-saved').checked=true;get('mfa-code').value='123456';get('mfa-confirm').listeners.click();await tick();await tick();assert.equal(get('mfa-secret').textContent,'');assert.equal(get('mfa-qr').src,undefined);assert(dispatched.includes('ly-session-updated'));get('mfa-disable').listeners.click();await tick();assert.equal(disabled,false);get('mfa-start').listeners.click();await tick();await tick();get('account-workspace').hidden=true;observe();assert.equal(get('mfa-recovery-codes').textContent,'');assert.equal(get('mfa-qr').src,undefined);
console.log('MFA UI passed: password-only challenge does not redirect, success clears credentials, binding/confirmation rotates session, cancel cannot disable, and leaving account clears QR/manual key/recovery codes.');
