import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';
import {createMailboxStore} from '../mailbox-store.mjs';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ly-mailbox-'));
try{
 let store=createMailboxStore(dir);const guest={kind:'guestbook',name:'路人',body:'公开留言 <script>test</script>',contact:'private@example.com',nonce:randomUUID()};
 store.submit(guest,'ip1');store.submit(guest,'ip1');assert.equal(store.list('all').messages.length,1);assert.equal(store.publicList().messages.length,0);
 let message=store.list('all').messages[0];store.update(message.id,{action:'approve',revision:message.revision});const pub=store.publicList().messages[0];assert.equal(pub.body,guest.body);for(const key of ['contact','submissionKey','revision','status','read'])assert.equal(pub[key],undefined);
 const letter={kind:'letter',name:'私信者',title:'仅给岛主',body:'不应公开的私信',contact:'secret@example.com',nonce:randomUUID()};store.submit(letter,'ip1');const secret=store.list('letter').messages[0];assert.throws(()=>store.update(secret.id,{action:'approve',revision:secret.revision}),e=>e.status===400);assert.equal(store.publicList().messages.length,1);
 assert.throws(()=>store.update(message.id,{action:'hide',revision:message.revision}),e=>e.status===409);message=store.list('guestbook').messages[0];store.update(message.id,{action:'reply',reply:'岛主回复',revision:message.revision});assert.equal(store.publicList().messages[0].reply,'岛主回复');message=store.list('guestbook').messages[0];store.update(message.id,{action:'archive',revision:message.revision});assert.equal(store.publicList().messages.length,0);message=store.list('archived').messages[0];store.update(message.id,{action:'restore',revision:message.revision});assert.equal(store.publicList().messages.length,1);
 for(let i=0;i<3;i++)store.submit({...guest,nonce:randomUUID()},'ip1');assert.throws(()=>store.submit({...guest,nonce:randomUUID()},'ip1'),e=>e.status===429);store=createMailboxStore(dir);assert.throws(()=>store.submit({...guest,nonce:randomUUID()},'ip1'),e=>e.status===429);assert.equal(store.list('all').messages.length,5);
 assert.throws(()=>store.submit({...guest,website:'bot',nonce:randomUUID()},'ip2'));assert.throws(()=>store.submit({...guest,body:'x'.repeat(3001),nonce:randomUUID()},'ip2'));assert.throws(()=>store.submit({...guest,contact:'invalid',nonce:randomUUID()},'ip2'));
 assert.equal(fs.statSync(path.join(dir,'mailbox.json')).mode&0o777,0o600);assert(!JSON.stringify(store.publicList()).includes('example.com'));console.log('Mailbox passed: moderation, private letters/contact, idempotency, revision conflicts, replies/archive, persisted rate limits and permissions.');
}finally{fs.rmSync(dir,{recursive:true,force:true});}
