import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';import {scryptSync,createHash} from 'node:crypto';import {Readable} from 'node:stream';import sharp from 'sharp';
const folder=fs.mkdtempSync(path.join(os.tmpdir(),'ly-media-check-'));Object.assign(process.env,{DATA_DIR:folder,NODE_ENV:'test',ADMIN_USERNAME:'ly',ADMIN_PASSWORD_HASH:'scrypt:test-salt:'+scryptSync('test-password','test-salt',64).toString('hex')});
const {handler,initializeData,markdown}=await import('../server.mjs');initializeData();const server=http.createServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;let groups=0;
const headers={'Content-Type':'application/json','Origin':base,'X-Requested-With':'rqly-editor'};const login=await fetch(base+'/api/auth/login',{method:'POST',headers,body:JSON.stringify({username:'ly',password:'test-password'})});headers.Cookie=login.headers.get('set-cookie').split(';')[0];headers['X-CSRF-Token']=(await login.json()).csrfToken;
const upload=(bytes,type='image/png',extra={})=>fetch(base+'/api/admin/media',{method:'POST',headers:{...headers,'Content-Type':type,...extra},body:bytes});
const json=(route,method='GET',value,extra={})=>fetch(base+route,{method,headers:{...headers,...extra},...(value?{body:JSON.stringify(value)}:{})});
try{
 const picture=await sharp({create:{width:320,height:160,channels:3,background:'#859e75'}}).png().toBuffer();
 const {createMediaStore}=await import('../media-store.mjs');const protectedStore=createMediaStore(path.join(folder,'protected'),{withdrawnHashes:[createHash('sha256').update(picture).digest('hex')]});const protectedInput=Readable.from([picture]);protectedInput.headers={'content-type':'image/png'};await assert.rejects(()=>protectedStore.upload(protectedInput),e=>e.status===400);assert(!fs.existsSync(path.join(folder,'protected/media')));groups++;
 assert.equal((await fetch(base+'/api/admin/media',{method:'POST',headers:{'Content-Type':'image/png'},body:picture})).status,401);assert.equal((await upload(picture,'image/png',{'X-CSRF-Token':''})).status,403);assert.equal((await upload(picture,'image/png',{Origin:'https://untrusted.example'})).status,403);groups++;
 assert.equal((await upload(Buffer.from('<svg onload="alert(1)"></svg>'),'image/svg+xml')).status,415);assert.equal((await upload(Buffer.from('not an image'),'image/png')).status,400);assert.equal((await upload(Buffer.alloc(8*1024*1024+1),'image/png')).status,413);assert.equal((await json('/qizui/api/admin/media')).status,404);groups++;
 let r=await upload(picture);assert.equal(r.status,201);const image=(await r.json()).image;assert(/^\/media\/[a-f0-9]{32}\.webp$/.test(image.url));assert.equal(image.width,320);assert.equal(image.height,160);assert.equal(fs.statSync(path.join(folder,'media',image.filename)).mode&0o777,0o600);assert.equal(fs.statSync(path.join(folder,'media')).mode&0o777,0o700);assert.equal((await fetch(base+image.url)).status,404);assert.equal((await json(image.url)).status,200);assert.equal((await json('/media/'+image.filename+'.json')).status,404);groups++;
 const html=markdown('![结构图]( '+image.url+' )');assert(html.includes('<img')&&html.includes('width="320"'));assert(markdown('![结构图]('+image.url+')').includes('width="320"'));assert(!markdown('![外部图片](https://external.example/image.jpg)').includes('<img'));groups++;
 r=await json('/api/admin/posts','POST',{title:'图片验收',body:'## 图示\n\n![结构图]('+image.url+')',kind:'note',topic:'工程',date:'2026-10-06',published:false});let post=(await r.json()).post;assert(!post.summary.includes('/media/'));assert.equal((await fetch(base+image.url)).status,404);
 r=await json('/api/admin/posts','PUT',{...post,published:true},{'If-Match':post.revision});post=(await r.json()).post;let publicImage=await fetch(base+image.url);assert.equal(publicImage.status,200);assert.equal(publicImage.headers.get('content-type'),'image/webp');assert.equal(publicImage.headers.get('cache-control'),'no-store');const publicHTML=(await(await json('/api/posts/'+post.slug)).json()).html;assert(publicHTML.includes(image.url));groups++;
 r=await json('/api/admin/posts','PUT',{...post,published:false},{'If-Match':post.revision});post=(await r.json()).post;assert.equal((await fetch(base+image.url)).status,404);assert.equal((await json(image.url)).status,200);groups++;
 const oriented=await sharp({create:{width:5000,height:1000,channels:3,background:'#9da58f'}}).withMetadata({orientation:6}).jpeg().toBuffer();r=await upload(oriented,'image/jpeg');assert.equal(r.status,201);const adjusted=(await r.json()).image;assert.equal(adjusted.width,480);assert.equal(adjusted.height,2400);const output=await sharp(fs.readFileSync(path.join(folder,'media',adjusted.filename))).metadata();assert.equal(output.orientation,undefined);assert.equal(output.exif,undefined);assert.equal(output.icc,undefined);groups++;
 const oversized=await sharp({create:{width:5000,height:5000,channels:3,background:'#9da58f'}}).png().toBuffer();assert.equal((await upload(oversized)).status,400);initializeData();assert((await(await json('/api/admin/media')).json()).images.some(i=>i.url===image.url));assert.equal((await json(image.url)).status,200);groups++;
 console.log(groups+' media groups passed: owner-only upload, origin/CSRF, formats/magic/limits, private storage, publication/withdrawal, safe Markdown, orientation/resize/metadata stripping and restart.');
}finally{await new Promise(r=>server.close(r));fs.rmSync(folder,{recursive:true,force:true});}
