import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';
import {scryptSync} from 'node:crypto';import {generateSync} from 'otplib';
import {createAdminMFA} from '../admin-mfa.mjs';import {createAdminAuth} from '../admin-auth.mjs';
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'ly-mfa-check-'));let clock=1800000000000,checks=0;
const password='isolated-mfa-password',initialHash='scrypt:fixture:'+scryptSync(password,'fixture',64).toString('hex');let passwordHash=initialHash;
const makeMfa=(dir=tmp)=>createAdminMFA({dataDir:dir,username:()=> 'ly',now:()=>clock});let mfa=makeMfa();
const makeAuth=()=>createAdminAuth({dataDir:tmp,username:()=> 'ly',passwordHash:()=>passwordHash,replacePasswordHash:(next,expected)=>{assert.equal(passwordHash,expected);passwordHash=next;},address:()=> 'isolated',mfa,secure:false});let auth=makeAuth();
const token=secret=>generateSync({secret,epoch:Math.floor(clock/1000)});const req=session=>({headers:session?{cookie:session.cookie,'x-csrf-token':session.csrfToken}:{}});
const response=()=>({headers:{},setHeader(name,value){this.headers[name.toLowerCase()]=value;}});
const login=async(code)=>{const res=response(),session=await auth.login(req(),res,{username:'ly',password,code});return {...session,cookie:res.headers['set-cookie'].split(';')[0]};};
const manage=async(session,action,input)=>{const res=response(),result=await auth.manageMFA(req(session),res,action,input);return {result,session:res.headers['set-cookie']?{cookie:res.headers['set-cookie'].split(';')[0],csrfToken:result.csrfToken}:session};};
const fails=async(work,status)=>{await assert.rejects(work,e=>e.status===status);};
let server;
try{
 auth.initialize();assert.deepEqual(mfa.status(),{enabled:false,recoveryCodesRemaining:0});assert(!fs.existsSync(path.join(tmp,'admin-mfa.json')));let first=await login();auth.initialize();assert(auth.session(req(first)));checks++;
 await fails(()=>manage(first,'setup',{currentPassword:'wrong'}),400);await fails(()=>auth.manageMFA({headers:{cookie:first.cookie}},response(),'setup',{currentPassword:password}),403);checks++;
 const setup=(await manage(first,'setup',{currentPassword:password})).result;assert(setup.qrCode.startsWith('data:image/png;base64,'));assert.equal(setup.recoveryCodes.length,10);assert.equal(setup.secret.length,32);for(const name of ['admin-mfa.json','admin-mfa-key.json'])assert.equal(fs.statSync(path.join(tmp,name)).mode&0o777,0o600);const persisted=fs.readFileSync(path.join(tmp,'admin-mfa.json'),'utf8');assert(!persisted.includes(setup.secret));assert(!persisted.includes(setup.recoveryCodes[0]));assert(!JSON.stringify(mfa.status()).includes(setup.secret));assert.equal(mfa.status().enabled,false);checks++;
 let other=await login();await fails(()=>manage(other,'confirm',{pendingId:setup.pendingId,code:token(setup.secret),recoverySaved:true}),409);await fails(()=>manage(first,'confirm',{pendingId:setup.pendingId,code:token(setup.secret),recoverySaved:false}),400);
 first=(await manage(first,'confirm',{pendingId:setup.pendingId,code:token(setup.secret),recoverySaved:true})).session;assert(mfa.status().enabled);assert(auth.session(req(first)));assert.equal(auth.session(req(other)),null);checks++;
 const noCookie=response();await fails(()=>auth.login(req(),noCookie,{username:'ly',password}),401);assert.equal(noCookie.headers['set-cookie'],undefined);await assert.rejects(()=>auth.login(req(),response(),{username:'ly',password}),e=>e.code==='MFA_REQUIRED');await fails(()=>login(token(setup.secret)),401);clock+=30000;const second=await login(token(setup.secret));assert(auth.session(req(second)));await fails(()=>login(token(setup.secret)),401);checks++;
 const concurrent=await Promise.allSettled([login(setup.recoveryCodes[0]),login(setup.recoveryCodes[0])]);assert.equal(concurrent.filter(r=>r.status==='fulfilled').length,1);assert.equal(mfa.status().recoveryCodesRemaining,9);mfa=makeMfa();auth=makeAuth();auth.initialize();await fails(()=>login(setup.recoveryCodes[0]),401);assert(auth.session(req(second)));checks++;
 const restored=path.join(tmp,'restored');fs.mkdirSync(restored);for(const name of ['admin-mfa.json','admin-mfa-key.json']){fs.copyFileSync(path.join(tmp,name),path.join(restored,name));fs.chmodSync(path.join(restored,name),0o600);}const restoredMfa=makeMfa(restored);clock+=30000;restoredMfa.verify(token(setup.secret));fs.renameSync(path.join(restored,'admin-mfa-key.json'),path.join(restored,'saved-key'));assert.throws(()=>restoredMfa.initialize(),e=>e.status===503);fs.renameSync(path.join(restored,'saved-key'),path.join(restored,'admin-mfa-key.json'));fs.chmodSync(path.join(restored,'admin-mfa-key.json'),0o644);assert.throws(()=>restoredMfa.initialize(),e=>e.status===503);checks++;
 await fails(()=>manage(second,'disable',{currentPassword:password}),401);const newSetup=(await manage(second,'setup',{currentPassword:password,code:token(setup.secret)})).result;assert(mfa.status().enabled);clock+=30000;await login(token(setup.secret));await manage(second,'cancel',{});await fails(()=>manage(second,'confirm',{pendingId:newSetup.pendingId,code:token(newSetup.secret),recoverySaved:true}),409);checks++;
 const expiring=(await manage(second,'setup',{currentPassword:password,code:setup.recoveryCodes[1]})).result;clock+=600001;await fails(()=>manage(second,'confirm',{pendingId:expiring.pendingId,code:token(expiring.secret),recoverySaved:true}),409);await manage(second,'cancel',{});checks++;
 const refreshed=await manage(second,'recovery',{currentPassword:password,code:setup.recoveryCodes[2]});first=refreshed.session;assert(auth.session(req(first)));assert.equal(auth.session(req(second)),null);assert.equal(mfa.status().recoveryCodesRemaining,10);await fails(()=>login(setup.recoveryCodes[3]),401);checks++;
 await fails(()=>auth.changePassword(req(first),response(),{currentPassword:password,newPassword:'replacement-password',confirmPassword:'replacement-password'}),401);const changed=await auth.changePassword(req(first),response(),{currentPassword:password,newPassword:'replacement-password',confirmPassword:'replacement-password',code:refreshed.result.recoveryCodes[0]});assert(changed.reauthenticate);assert.equal(auth.session(req(first)),null);passwordHash=initialHash;assert(mfa.status().enabled);checks++;
 first=await login(refreshed.result.recoveryCodes[1]);const disabled=await manage(first,'disable',{currentPassword:password,code:refreshed.result.recoveryCodes[2]});assert.equal(mfa.status().enabled,false);assert(auth.session(req(disabled.session)));assert.equal(auth.session(req(first)),null);await login();checks++;
 const rateDir=path.join(tmp,'rate');fs.mkdirSync(rateDir);const rate=makeMfa(rateDir),pending=await rate.begin('a'.repeat(64));rate.confirm('a'.repeat(64),{pendingId:pending.pendingId,code:token(pending.secret),recoverySaved:true});const wrong=String((Number(token(pending.secret))+111111)%1000000).padStart(6,'0');for(let i=0;i<10;i++)assert.throws(()=>rate.verify(wrong),e=>e.status===401);assert.throws(()=>makeMfa(rateDir).verify(pending.recoveryCodes[0]),e=>e.status===429);clock+=900001;makeMfa(rateDir).verify(pending.recoveryCodes[0]);checks++;
 const driftDir=path.join(tmp,'drift');fs.mkdirSync(driftDir);const drift=makeMfa(driftDir),d=await drift.begin('b'.repeat(64));drift.confirm('b'.repeat(64),{pendingId:d.pendingId,code:token(d.secret),recoverySaved:true});clock+=30000;drift.verify(generateSync({secret:d.secret,epoch:Math.floor(clock/1000)+30}));assert.throws(()=>drift.verify(generateSync({secret:d.secret,epoch:Math.floor(clock/1000)+90})),e=>e.status===401);checks++;
 // Exercise the actual HTTP routes and both host-based login pages in a clean data directory.
 const httpDir=path.join(tmp,'http');process.env.DATA_DIR=httpDir;process.env.NODE_ENV='test';process.env.ADMIN_USERNAME='ly';process.env.ADMIN_PASSWORD_HASH=initialHash;const {handler,initializeData}=await import('../server.mjs');initializeData();server=http.createServer(handler);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port;const headers={'Content-Type':'application/json',Origin:base,'X-Requested-With':'rqly-editor'};
 let r=await fetch(base+'/api/auth/login',{method:'POST',headers,body:JSON.stringify({username:'ly',password})});assert.equal(r.status,200);const cookie=r.headers.get('set-cookie').split(';')[0],session=await r.json();const adminHeaders={...headers,Cookie:cookie,'X-CSRF-Token':session.csrfToken};
 r=await fetch(base+'/api/admin/mfa/setup',{method:'POST',headers:{...adminHeaders,Origin:'https://untrusted.example'},body:JSON.stringify({currentPassword:password})});assert.equal(r.status,403);
 const post=async(action,body,custom=adminHeaders)=>fetch(base+'/api/admin/mfa/'+action,{method:'POST',headers:custom,body:JSON.stringify(body)});
 r=await post('setup',{currentPassword:password});assert.equal(r.status,200);const h=await r.json();r=await post('confirm',{pendingId:h.pendingId,recoverySaved:true,code:generateSync({secret:h.secret})});assert.equal(r.status,200);assert.equal((await fetch(base+'/api/admin/mfa',{headers:adminHeaders})).status,401);
 for(const host of ['rqly.com','7zui.com']){r=await fetch(base+'/login',{headers:{Host:host}});assert.equal(r.status,200);assert((await r.text()).includes('login-mfa-code'));r=await fetch(base+'/api/auth/login',{method:'POST',headers:{...headers,Host:host},body:JSON.stringify({username:'ly',password})});assert.equal(r.status,401);assert.equal((await r.json()).code,'MFA_REQUIRED');assert(!r.headers.has('set-cookie'));r=await fetch(base+'/api/auth/login',{method:'POST',headers:{...headers,Host:host},body:JSON.stringify({username:'ly',password,code:h.recoveryCodes[host==='rqly.com'?0:1]})});assert.equal(r.status,200);}
 for(const route of ['/admin-mfa.json','/admin-mfa-key.json','/admin-mfa.mjs'])assert.equal((await fetch(base+route)).status,404);assert.equal((await fetch(base+'/api/admin/mfa')).status,401);checks++;
 console.log(checks+' MFA groups passed: opt-in, encrypted storage, CSRF/origin, activation, session rotation, replay, concurrent single-use recovery, restart/restore, rebind, expiry, disable, password changes, rate limits, time drift and both hosts.');
}finally{if(server)await new Promise(resolve=>server.close(resolve));fs.rmSync(tmp,{recursive:true,force:true});}
